# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-28 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180829_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
